algoviewer/urls.py
from django.urls import path

from . import views

app_name = "algoviewer"

urlpatterns = [
    path('', views.algoviewer_home, name="home"),
]

calculator/urls.py
from django.urls import path

from . import views

app_name = "calculator"

urlpatterns = [
    path('', views.calculator_view, name="form"),
]

portfolio/urls.py
from django.conf import Settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import views
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('calculator/', include('calculator.urls')),
    path('algoviewer/', include('algoviewer.urls')),
    path('', views.homepage, name='home'),
    path('about/', views.about, name='about'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

algoviewer/models.py
from django.db import models

# Create your models here.

calculator/models.py
from django.db import models

class Calculator(models.Model):
    name = models.TextField(default="placeholder")
    mhs = models.FloatField()
    power = models.IntegerField()
    price = models.FloatField()  # GBP
    kwh_price = models.FloatField()
    efficiency = models.FloatField()
    epp = models.FloatField()
    roi = models.FloatField()
    # year
    # month
    # day
    # week

calculator/forms.py
from django import forms
from . import models

class CalculateGpu(forms.ModelForm):
    class Meta:
        model = models.Calculator
        fields = ["mhs", "power", "price", "kwh_price"]

portfolio/forms.py
from django import forms

class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

algoviewer/views.py
from django.shortcuts import render

def algoviewer_home(request):
    return render(request, "algoviewer_home.html")

calculator/views.py
from django.shortcuts import render
from . import forms, models
from .profitability_calculator.gpu import GPU


def calculator_view(request):
    if request.method == "POST":
        form = forms.CalculateGpu(request.POST, request.FILES)  # might not need request.FILES. Check later.
        if form.is_valid():
            instance = form.save(commit=False)
            # calculator = models.Calculator  # create Calculator model object
            gpu = GPU(mhs=instance.mhs, name=instance.name, power=instance.power,
                      price=instance.price, kwh_price_gbp=instance.kwh_price)
            calculator = models.Calculator(name="test",
                            mhs=gpu.mhs, power=gpu.power, price=gpu.price,
                            kwh_price=instance.kwh_price, efficiency=gpu.efficiency,
                            epp=gpu.epp, roi=gpu.roi)
            return render(request, 'calculator/calculator_form.html', {'calculator':calculator})
    return render(request, 'calculator/calculator_form.html')

portfolio/views.py
from django.core.mail import send_mail, BadHeaderError
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import ContactForm

def homepage(request):
    if request.method == "GET":
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data["subject"]
            from_email = form.cleaned_data["from_email"]
            message = "from_email=" + from_email + "\n\n" + form.cleaned_data["message"]
            try:
                send_mail(subject, message, "contactform@patrykdobbek.com", ["p.dobbek@pm.me"], fail_silently=False)
                messages.success(request, "Email sent succesfully. Thank you!")
                return redirect("home")
            except BadHeaderError:
                return HttpResponse("Invalid header found.")
        else:
            messages.error(request, "Invalid form submission.")
            messages.error(request, form.errors)
            return redirect("home")
    return render(request, "homepage.html")

def about(request):
    return render(request, "about.html")

algoviewer/templates/algoviewer_home.html
{% extends 'base_layout.html' %}
{% load static %}

{% block extrahead %}
  <link rel="stylesheet" href="{% static '/css/algoviewer_main.css' %}">
{% endblock %}

{% block content %}
  <div>
    <h2>AlgoViewer</h2>
  </div>
{% endblock %}

{% extrajs %}
  <script src="{% static '/js/placeholder.js' %}"></script>
{% endblock %}

calculator/templates/calculator/calculator_form.html
{% extends 'base_layout.html' %}

{% block content %}
  <div class="calculator-form">
        <div class="calculator">
          <h2>Calculate GPU Profitability</h2>
          <form class="site-form" action="{% url 'calculator:form' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <label for="mhs">Hashrate (MHs)</label>
            <input type="text" name="mhs" id="mhs" value="{{ calculator.mhs }}" required>

            <label for="power">Power consumption (W)</label>
            <input type="text" name="power" id="power" value="{{ calculator.power }}" required>

            <label for="price">Price (GBP)</label>
            <input type="text" name="price" id="price" value="{{ calculator.price }}" required>

            <label for="kwh_price">Electricity cost (KWh)</label>
            <input type="text" name="kwh_price" id="kwh_price" value="{{ calculator.kwh_price }}" required>

            <input type="submit" value="Submit">
          </form>
        </div>
        
        <div class="gpu-details">
          <!-- Display calculated data below -->
          <p>Hashrate (MHs) = {{ calculator.mhs }}</p>
          <p>Power consumption (W) = {{ calculator.power }}</p>
          <p>Price (GBP) = {{ calculator.price }}</p>
          <p>Electricity cost (KWh) = {{ calculator.kwh_price }}</p>
          <p>Efficiency (MHs/W) = {{ calculator.efficiency }}</p>
          <p>EPP (efficiency/price) = {{ calculator.epp }}</p>
          <p>ROI (days) = {{ calculator.roi }}</p>
        </div>
  </div>
{% endblock %}

templates/about.html
{% extends 'base_layout.html' %}

{% block content %}
  <h2>This is the about page.</h2>
  <p>Eventually I would like to have more details about myself here.</p>
  <p>(mostly what's on my CV.)</p>
{% endblock %}

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="img/ico" href="{% static '/img/favicon.ico' %}"/>

    <!---------------------------------SWIPER  CSS--------------------------------->
    <link rel="stylesheet" href="{% static '/css/swiper-bundle.min.css' %}">
    <!-------------------------------------CSS------------------------------------->
    <link rel="stylesheet" href="{% static '/css/styles.css' %}">
    <!-----------------------------------UNICONS----------------------------------->
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v3.0.1/css/line.css">
    
    <title>Patryk Dobbek</title>

    {% block extrahead %}
    {% endblock %}
  </head>
  <body>

    <header class="header" id="header">
      <nav class="nav container">
        <a href="#" class="nav__logo">Patryk Dobbek</a>

        <div class="nav__menu" id="nav-menu">
          <ul class="nav__list grid">
            <li class="nav__item">
              <a href="#home" class="nav__link">
                <i class="uil uil-home-alt nav__icon"></i> Home
              </a>
            </li>
            <li class="nav__item">
              <a href="#about" class="nav__link">
                <i class="uil uil-user nav__icon"></i> About Me
              </a>
            </li>
            <li class="nav__item">
              <a href="#skills" class="nav__link">
                <i class="uil uil-brain nav__icon"></i> Skills
              </a>
            </li>
            <li class="nav__item">
              <a href="#education" class="nav__link">
                <i class="uil uil-graduation-cap nav__icon"></i> Education
              </a>
            </li>
            <li class="nav__item">
              <a href="#projects" class="nav__link">
                <i class="uil uil-brackets-curly nav__icon"></i> My Projects
              </a>
            </li>
            <li class="nav__item">
              <a href="#contact" class="nav__link">
                <i class="uil uil-message nav__icon"></i> Contact Me
              </a>
            </li>
          </ul>
          <i class="uil uil-times nav__close nav__icon" id="nav-close"></i>
        </div>

        <div class="nav__btns">
          <div class="nav__toggle" id="nav-toggle">
            <i class="uil uil-apps"></i>
          </div>
        </div>
      </nav>
    </header>

    <main class="main">
      {% block content %}
      {% endblock %}
    </main>

    <footer class="footer">
      <div class="footer__bg">
        <div class="footer__container container grid">
          <div>
            <h1 class="footer__title">Patryk Dobbek</h1>
            <span class="footer__subtitle">Graduate Developer</span>
          </div>

          <div class="footer__socials">
            <a href="https://www.linkedin.com/in/patryk-dobbek/" target="_blank" class="footer__social">
              <i class="uil uil-linkedin"></i>
            </a>
            <a href="https://github.com/pdobbek/" target="_blank" class="footer__social">
              <i class="uil uil-github"></i>
            </a>
          </div>
        </div>
      </div>
    </footer>

    <!-------------------------------------MAIN JS------------------------------------->
    <script src="{% static '/js/main.js' %}"></script>
    {% block extrajs %}
    {% endblock %}
  </body>
</html>

templates/messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-dismissible alert-success">
      <button type="button" class="close" data-dismiss="alert">
      ×
      </button>
      <strong>{{message}}<strong>
    </div>
 {% endfor %}
{% endif %}